services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped    
    ports:
      - "5678:5678"
    environment:
      - WEBHOOK_URL= # <--- Dominio o Subdominio
      - GENERIC_TIMEZONE=Europe/Madrid
      - TZ=Europe/Madrid
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password  
      - N8N_SECURE_COOKIE=false
      - N8N_EMAIL_MODE= # <--- Credencial de correo
      - N8N_SMTP_HOST= # <--- Credencial de correo
      - N8N_SMTP_PORT= # <--- Credencial de correo
      - N8N_SMTP_USER= # <--- Credencial de correo
      - N8N_SMTP_PASS= # <--- Credencial de correo
      - N8N_SMTP_SENDER= # <--- Credencial de correo - colocar entre ""
      - N8N_SMTP_SSL= # <--- Credencial de correo
      - N8N_PROTOCOL=https
      - DB_TYPE=postgresdb 
      - DB_POSTGRESDB_HOST=postgres 
      - DB_POSTGRESDB_PORT=5432 
      - DB_POSTGRESDB_DATABASE=n8n 
      - DB_POSTGRESDB_USER=n8n 
      - DB_POSTGRESDB_PASSWORD= # <--- Colocar contraseña
    volumes:
      - n8n_data:/home/node/.n8n 
      - ./local_files:/files         
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: n8n-postgres
    restart: unless-stopped 
    ports:
      - 5430:5432   
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD= # <--- Colocar contraseña
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data      

  redis:
    image: redis:latest
    container_name: n8n-redis
    restart: unless-stopped
    volumes:
      - ./redis_storage:/data

volumes:
  n8n_data:
  postgres_data: