services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped    
    ports:
      - "5678:5678"
    environment:
      - TRUST_PROXY=true
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_PUSH_BACKEND=websocket
      - VUE_APP_URL_BASE_API=https://${SUBDOMAIN}.${DOMAIN_NAME}/rest
      - N8N_CORS_ALLOW_METHODS=GET,POST,OPTIONS
      - N8N_CORS_ALLOW_HEADERS=Authorization,Content-Type
      - GENERIC_TIMEZONE=Europe/Madrid
      - N8N_QUEUE_TYPE=redis
      - N8N_QUEUE_HOST=redis
      - N8N_QUEUE_PORT=6379
      - N8N_QUEUE_NAME=n8n
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password  
      - N8N_SECURE_COOKIE=false
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST={SMTP_HOST}
      - N8N_SMTP_PORT={SMTP_PORT}
      - N8N_SMTP_USER={SMTP_EMAIL}
      - N8N_SMTP_PASS={SMTP_PASS}
      - N8N_SMTP_SENDER="N8N <{SMTP_EMAIL}>"
      - N8N_SMTP_SSL=false
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_LOG_LEVEL=debug
      - DB_TYPE=postgresdb 
      - DB_POSTGRESDB_HOST=postgres 
      - DB_POSTGRESDB_PORT=5432 
      - DB_POSTGRESDB_DATABASE=n8n 
      - DB_POSTGRESDB_USER=n8n 
      - DB_POSTGRESDB_PASSWORD={POSTGRESDB_PASSWORD}
    volumes:
      - n8n_data:/home/node/.n8n 
      - ./local_files:/files
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    container_name: n8n-postgres
    restart: unless-stopped 
    ports:
      - 5430:5432   
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD={POSTGRESDB_PASSWORD}
      - POSTGRES_DB=n8n
    volumes:
      - ./postgres_data:/var/lib/postgresql/data      

  redis:
    image: redis:latest
    container_name: n8n-redis
    restart: unless-stopped
    volumes:
      - ./redis_storage:/data

volumes:
  n8n_data:
  postgres_data: